### ISSUE TITLE
Asset Source Broken / Added without cofing

### ISSUE THREAD

**Issue by ovsw** [dennispassway/sanity-plugin-media-library#13]
### Overview: 

1. the asset source is added just by installing the plugin, to all image fields (potentially unwanted behavior) 
2. when adding the plugin as an asset source manually, a broken option appears, besides the automatically-added one, that causes Sanity to crash when used.

### Details

1. just by doing `sanity install media-library`, without any further config, all image fields have a "Media Library" source.
![image](https://user-images.githubusercontent.com/35622133/104834847-dbc90100-58aa-11eb-9c41-749e2b6dea1d.png)

2. When adding the custom asset source for all image fields, the result looks like this, with an empty option appearing below the automatically-added one from point 1:
![image](https://user-images.githubusercontent.com/35622133/104834857-0915af00-58ab-11eb-9508-af4c65c80659.png)
If clicked, that option will crash Desk Tool.

Instructions were followed to added the custom asset source:
```
// sanity.js
    {
      "implements": "part:@sanity/form-builder/input/image/asset-source",
      "path": "./assetSource.js"
    }
```
and 
```
// assetSource.js
import AssetSource from "part:sanity-plugin-media-library/asset-source";
export default [AssetSource];
```

### Steps to reproduce:

1. `sanity install media-library`;
2. you will see the custom asset source added, even though it's not supposed to be there;
3. add custom asset source as described in the docs;
4. you will get the broken custom asset source option appearing for all fields,
5. when clicking that asset source Desk tool will crash with:
Stack trace:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ImageInput`.
    at createFiberFromTypeAndProps (/static/js/vendor.bundle.js:27107:21)
    at createFiberFromElement (/static/js/vendor.bundle.js:27130:15)
    at createChild (/static/js/vendor.bundle.js:16770:28)
    at reconcileChildrenArray (/static/js/vendor.bundle.js:17042:25)
    at reconcileChildFibers (/static/js/vendor.bundle.js:17447:14)
    at reconcileChildren (/static/js/vendor.bundle.js:19911:28)
    at updateFragment (/static/js/vendor.bundle.js:20119:3)
    at beginWork (/static/js/vendor.bundle.js:21791:14)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3330:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:3379:16)
```
Component Stack: 
```
    in div (created by Fieldset)
    in div (created by Fieldset)
    in div (created by Fieldset)
    in fieldset (created by Fieldset)
    in div (created by Fieldset)
    in Fieldset (created by UploadTargetFieldset)
    in UploadTargetFieldset (created by ImageInput)
    in ImageInput (created by SanityImageInput)
    in SanityImageInput (created by withDocument(SanityImageInput))
    in withDocument(SanityImageInput) (created by FormBuilderInput)
    in ChangeIndicatorProvider (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by Tabs)
    in div (created by Tabs)
    in div (created by Tabs)
    in div (created by Tabs)
    in Tabs (created by withDocument(Tabs))
    in withDocument(Tabs) (created by FormBuilderInput)
    in ChangeIndicatorProvider (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by Field)
    in div (created by Field)
    in Field (created by ObjectInput)
    in div (created by ObjectInput)
    in div (created by ObjectInput)
    in ObjectInput (created by FormBuilderInput)
    in ChangeIndicatorProvider (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by SanityFormBuilder)
    in FormBuilderContext (created by SanityFormBuilderContext)
    in SanityFormBuilderContext (created by SanityFormBuilder)
    in SanityFormBuilder (created by EditForm)
    in form (created by EditForm)
    in EditForm (created by FormView)
    in div (created by ForwardRef(RegionsWithIntersections))
    in div (created by ForwardRef(RegionsWithIntersections))
    in ForwardRef(RegionsWithIntersections) (created by StickyOverlay)
    in StickyOverlay (created by OverlayEnabled)
    in Tracker (created by OverlayEnabled)
    in OverlayEnabled (created by FormView)
    in div (created by FormView)
    in FormView (created by DocumentPanel)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by DocumentPanel)
    in div (created by DocumentPanel)
    in BoundaryElementProvider (created by DocumentPanel)
    in PortalProvider (created by DocumentPanel)
    in div (created by DocumentPanel)
    in DocumentPanel (created by DocumentPane)
    in div (created by DocumentPane)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by EnabledChangeConnectorRoot)
    in Tracker (created by EnabledChangeConnectorRoot)
    in EnabledChangeConnectorRoot (created by DocumentPane)
    in div (created by KeyboardShortcutResponder)
    in KeyboardShortcutResponder (created by GetHookCollectionState)
    in GetHookCollectionState (created by RenderActionCollectionState)
    in RenderActionCollectionState (created by DocumentActionShortcuts)
    in DocumentActionShortcuts (created by DocumentPane)
    in DocumentPane (created by DocumentPaneProvider)
    in DocumentHistoryProvider (created by DocumentPaneProvider)
    in DocumentPaneProvider
    in StreamingComponent
    in StreamingComponent (created by Context.Consumer)
    in WithInitialValueWrapper (created by DeskToolPane)
    in DeskToolPane (created by DeskToolPanes)
    in SplitPaneWrapper (created by DeskToolPanes)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in PanesSplitController (created by DeskToolPanes)
    in div (created by DeskToolPanes)
    in DeskToolPanes (created by DeskTool)
    in DeskTool (created by withRouter(DeskTool))
    in withRouter(DeskTool) (created by DeskToolPaneStateSyncer)
    in DeskToolPaneStateSyncer (created by DeskTool)
    in DeskToolFeaturesProvider (created by DeskTool)
    in DeskTool (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutRoot)
    in RouterProvider (created by DefaultLayoutRoot)
    in LoginWrapper (created by DefaultLayoutRoot)
    in DefaultLayoutRoot (created by AppProvider)
    in div (created by styled.div)
    in styled.div (created by Card)
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by Card)
    in Card (created by Styled(Card))
    in Styled(Card) (created by AppProvider)
    in SnackbarProvider (created by AppProvider)
    in LayerProvider (created by AppProvider)
    in PortalProvider (created by AppProvider)
    in UserColorManagerProvider (created by AppProvider)
    in AppProvider (created by SanityRoot)
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by SanityRoot)
    in SanityRoot
    in AppContainer
```

### Environment:
Reproducible on the Sanity Blog Schema clean install.
Packages and versions used:
```
  "@sanity/base": "^2.1.6",
    "@sanity/components": "^2.1.4",
    "@sanity/core": "^2.1.4",
    "@sanity/default-layout": "^2.1.6",
    "@sanity/default-login": "^2.1.4",
    "@sanity/desk-tool": "^2.1.6",
    "@sanity/vision": "^2.1.4",
    "prop-types": "^15.7",
    "react": "^17.0",
    "react-dom": "^17.0",
    "sanity-plugin-media-library": "^1.0.2"
```

**Comment by ovsw** [comment]
PS: love the plugin otherwise, would really like to use it for a current project where the client needs to work with a **ton** of images and they absolutely require proper ALT tags for all - managing the ALT tags in a centralized location would be a godsend.

**Comment by Aratramba** [comment]
I'm seeing this behaviour as well. The other media plugins (media and cloudinary) have the same behaviour. [Default sanity behaviour](https://www.sanity.io/docs/custom-asset-sources#defining-asset-sources-globally-8a7448076430) is that all sources are enabled, unless you specify a custom asset sources config. If we want to overwrite all asset sources, it should be the `asset-sources` part, not `asset-source`

```
{
  "implements": "part:@sanity/form-builder/input/image/asset-sources",
  "path": "./assetSources.js"
}
```

Can you confirm this fixes it for you @ovsw ?

**Comment by ovsw** [comment]
@Aratramba confirmed, thanks for spotting that!

**Comment by Aratramba** [comment]
Thanks for confirming @ovsw. I've fixed the example in the readme.
